# include modules
include(CheckCCompilerFlag)
include(CheckCXXCompilerFlag)
include(${CMAKE_CURRENT_LIST_DIR}/value.cmake)

get_property(enabled_languages GLOBAL PROPERTY ENABLED_LANGUAGES)

macro(check_flag)
  foreach(v ${ARGN})
    if(C IN_LIST enabled_languages)
      check_c_compiler_flag(${v} CC${v})
      if(CC${v})
        value_append(CMAKE_C_FLAGS ${v})
      endif()
    endif()
    if(CXX IN_LIST enabled_languages)
      check_cxx_compiler_flag(${v} CXX${v})
      if(CXX${v})
        value_append(CMAKE_CXX_FLAGS ${v})
      endif()
    endif()
  endforeach()
endmacro()

macro(check_flag_cc)
  foreach(v ${ARGN})
    if(C IN_LIST enabled_languages)
      check_c_compiler_flag(${v} CC${v})
      if(CC${v})
        value_append(CMAKE_C_FLAGS ${v})
      endif()
    endif()
  endforeach()
endmacro()

macro(check_flag_xx)
  foreach(v ${ARGN})
    if(CXX IN_LIST enabled_languages)
      check_cxx_compiler_flag(${v} CXX${v})
      if(CXX${v})
        value_append(CMAKE_CXX_FLAGS ${v})
      endif()
    endif()
  endforeach()
endmacro()
