# include modules
include(CheckCCompilerFlag)
include(CheckCXXCompilerFlag)
include(${CMAKE_CURRENT_LIST_DIR}/value.cmake)

get_property(lang GLOBAL PROPERTY ENABLED_LANGUAGES)

macro(check_flag)
  foreach(v ${ARGN})
    if(C IN_LIST lang)
      check_c_compiler_flag(${v} CC${v})
      if(CC${v})
        append_flag_cc(${v})
      endif()
    endif()
    if(CXX IN_LIST lang)
      check_cxx_compiler_flag(${v} CXX${v})
      if(CXX${v})
        append_flag_xx(${v})
      endif()
    endif()
  endforeach()
endmacro()

macro(check_flag_cc)
  foreach(v ${ARGN})
    if(C IN_LIST lang)
      check_c_compiler_flag(${v} CC${v})
      if(CC${v})
        append_flag_cc(${v})
      endif()
    endif()
  endforeach()
endmacro()

macro(check_flag_xx)
  foreach(v ${ARGN})
    if(CXX IN_LIST lang)
      check_cxx_compiler_flag(${v} CXX${v})
      if(CXX${v})
        append_flag_xx(${v})
      endif()
    endif()
  endforeach()
endmacro()

if("${CMAKE_C_COMPILER_ID}" MATCHES "GNU" OR "${CMAKE_C_COMPILER_ID}" MATCHES "(Apple)?[Cc]lang" OR
  "${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU" OR "${CMAKE_CXX_COMPILER_ID}" MATCHES "(Apple)?[Cc]lang")
  append_flag(-Wall -Wextra -Wpedantic)
  check_flag(-Wdouble-promotion)
  check_flag(-Wnull-dereference)
  check_flag(-Wmissing-include-dirs)
  check_flag(-Wswitch-default -Wswitch-enum)
  check_flag(-Walloca)
  check_flag(-Wattributes)
  check_flag(-Wfloat-equal)
  check_flag(-Wshadow)
  check_flag(-Wundef)
  check_flag(-Wunused -Wunused-macros)
  check_flag(-Wcast-qual -Wcast-align)
  check_flag(-Wconversion)
  check_flag(-Wdate-time)
  check_flag(-Waggregate-return)
  check_flag(-Wmissing-declarations)
  check_flag(-Wpacked -Wpadded)
  check_flag(-Wredundant-decls)
  check_flag(-Winline)
  check_flag(-Winvalid-pch)
  check_flag(-Wdisabled-optimization)
  check_flag(-Wstack-protector)
  check_flag_cc(-Winit-self)
  check_flag_cc(-Wc++-compat)
  check_flag_cc(-Wbad-function-cast)
  check_flag_cc(-Wstrict-prototypes)
  check_flag_cc(-Wold-style-definition)
  check_flag_cc(-Wmissing-prototypes)
  check_flag_cc(-Wnested-externs)
elseif("${CMAKE_C_COMPILER_ID}" MATCHES "MSVC" OR "${CMAKE_CXX_COMPILER_ID}" MATCHES "MSVC")
  add_compile_definitions(_CRT_SECURE_NO_WARNINGS)
  append_flag(/nologo /W4 /sdl)
  if("${VCPKG_TARGET_TRIPLET}" MATCHES "(.*)windows-static(.*)")
    value_remove(CMAKE_CXX_FLAGS_DEBUG /MDd)
    value_append(CMAKE_CXX_FLAGS_DEBUG /MTd)
    value_remove(CMAKE_CXX_FLAGS_RELEASE /MD)
    value_append(CMAKE_CXX_FLAGS_RELEASE /MT)
    value_remove(CMAKE_CXX_FLAGS_MINSIZEREL /MD)
    value_append(CMAKE_CXX_FLAGS_MINSIZEREL /MT)
    value_remove(CMAKE_CXX_FLAGS_RELWITHDEBINFO /MD)
    value_append(CMAKE_CXX_FLAGS_RELWITHDEBINFO /MT)
  endif()
endif()
# GNU
if("${CMAKE_C_COMPILER_ID}" MATCHES "GNU" OR "${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU")
  check_flag(-Wstringop-overflow -Wstringop-truncation)
  check_flag(-Walloc-zero)
  check_flag(-Wduplicated-branches -Wduplicated-cond)
  check_flag(-Wzero-length-bounds)
  check_flag(-Wtrampolines)
  check_flag(-Wunsafe-loop-optimizations)
  check_flag(-Wno-pedantic-ms-format)
  check_flag(-Wlogical-op)
endif()
# Clang
if("${CMAKE_C_COMPILER_ID}" MATCHES "(Apple)?[Cc]lang" OR "${CMAKE_CXX_COMPILER_ID}" MATCHES "(Apple)?[Cc]lang")
  check_flag(-Wshadow-all)
  check_flag(-Wzero-length-array)
endif()
