# core
macro(value_prefix variable)
  foreach(v ${ARGN})
    if(${variable})
      string(FIND "${${variable}}" ${v} r)
      if(${r} EQUAL -1)
        set(${variable} "${v} ${${variable}}")
      endif()
      unset(r)
    else()
      set(${variable} ${v})
    endif()
  endforeach()
endmacro()
macro(value_append variable)
  foreach(v ${ARGN})
    if(${variable})
      string(FIND "${${variable}}" ${v} r)
      if(${r} EQUAL -1)
        set(${variable} "${${variable}} ${v}")
      endif()
      unset(r)
    else()
      set(${variable} ${v})
    endif()
  endforeach()
endmacro()
macro(value_remove variable)
  foreach(v ${ARGN})
    string(REPLACE "${v} " "" ${variable} "${${variable}}")
    string(REPLACE "${v}" "" ${variable} "${${variable}}")
  endforeach()
endmacro()
# FLAGS
macro(append_flag)
  foreach(v ${ARGN})
    value_append(CMAKE_C_FLAGS ${v})
    value_append(CMAKE_CXX_FLAGS ${v})
  endforeach()
endmacro()
macro(remove_flag)
  foreach(v ${ARGN})
    value_remove(CMAKE_C_FLAGS ${v})
    value_remove(CMAKE_CXX_FLAGS ${v})
  endforeach()
endmacro()
# CFLAGS
macro(append_flag_cc)
  foreach(v ${ARGN})
    value_append(CMAKE_C_FLAGS ${v})
  endforeach()
endmacro()
macro(remove_flag_cc)
  foreach(v ${ARGN})
    value_remove(CMAKE_C_FLAGS ${v})
  endforeach()
endmacro()
# CXXFLAGS
macro(append_flag_xx)
  foreach(v ${ARGN})
    value_append(CMAKE_CXX_FLAGS ${v})
  endforeach()
endmacro()
macro(remove_flag_xx)
  foreach(v ${ARGN})
    value_remove(CMAKE_CXX_FLAGS ${v})
  endforeach()
endmacro()
# CUDAFLAGS
macro(append_flag_cu)
  foreach(v ${ARGN})
    value_append(CMAKE_CUDA_FLAGS ${v})
  endforeach()
endmacro()
macro(remove_flag_cu)
  foreach(v ${ARGN})
    value_remove(CMAKE_CUDA_FLAGS ${v})
  endforeach()
endmacro()
