name: freebsd
on:
  workflow_dispatch:
jobs:
  FreeBSD:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        include: [
          { name: dbg, preset: debug, target: install },
          { name: rel, preset: release, target: install/strip },
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - uses: vmactions/freebsd-vm@v0.1.6
        env:
          VCPKG_INSTALLATION_ROOT: ~/vcpkg
        with:
          copyback: true
          prepare: |
            pkg install -y binutils cmake gmake gcc
            pkg install -y ninja zip unzip curl git pkgconf
          envs: VCPKG_INSTALLATION_ROOT
          run: |
            git clone https://github.com/Microsoft/vcpkg.git $VCPKG_INSTALLATION_ROOT --depth 1
            $VCPKG_INSTALLATION_ROOT/bootstrap-vcpkg.sh -disableMetrics
            cmake --preset=${{ matrix.preset }} -DBUILD_TESTING=ON
            cmake --build --preset=${{ matrix.preset }} --target ${{ matrix.target }} --parallel
            ctest --preset=${{ matrix.preset }} --parallel
      - uses: actions/upload-artifact@v2
        with:
          name: freebsd-x64-${{ matrix.name }}
          path: install/bin/*
          if-no-files-found: ignore
