name: freebsd
on:
  workflow_dispatch:
jobs:
  FreeBSD:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        include: [
          { name: dbg, sanitizer: 1, buildtype: Debug, target: install },
          { name: rel, sanitizer: 0, buildtype: Release, target: install/strip },
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - uses: vmactions/freebsd-vm@v0.1.6
        env:
          CC: clang
          CXX: clang++
          VCPKG_INSTALLATION_ROOT: ~/vcpkg
        with:
          copyback: true
          prepare: |
            pkg install -y git
            pkg install -y zip
            pkg install -y curl
            pkg install -y unzip
            pkg install -y cmake
            pkg install -y gmake
            pkg install -y ninja
            pkg install -y pkgconf
          envs: 'CC CXX VCPKG_INSTALLATION_ROOT'
          run: |
            git clone https://github.com/Microsoft/vcpkg.git $VCPKG_INSTALLATION_ROOT --single-branch --branch 2021.12.31
            $VCPKG_INSTALLATION_ROOT/bootstrap-vcpkg.sh -disableMetrics
            cmake -S . -B build \
              -DBUILD_TESTING=ON \
              -DENABLE_WARNINGS=ON \
              -DCMAKE_INSTALL_PREFIX=install \
              -DVCPKG_TARGET_TRIPLET=x64-freebsd \
              -DENABLE_SANITIZE=${{matrix.sanitizer}} \
              -DCMAKE_BUILD_TYPE=${{matrix.buildtype}}
            cmake --build build --target ${{matrix.target}}
            cmake --build build -t test
      - uses: actions/upload-artifact@v2
        with:
          name: freebsd-x64-${{matrix.name}}
          path: install/bin/*
          if-no-files-found: ignore
