name: freebsd
on:
  workflow_dispatch:
jobs:
  FreeBSD:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        include: [
          { name: dbg, sanitizer: 1, buildtype: Debug, target: install },
          { name: rel, sanitizer: 0, buildtype: Release, target: install/strip },
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - uses: vmactions/freebsd-vm@v0.1.6
        env:
          CC: clang
          CXX: clang++
        with:
          copyback: true
          prepare: |
            pkg install -y git zip curl unzip cmake gmake ninja pkgconf
          envs: 'CC CXX'
          run: |
            cmake -S . -B build -G Ninja \
              -DBUILD_TESTING=ON \
              -DENABLE_WARNINGS=ON \
              -DCMAKE_INSTALL_PREFIX=install \
              -DENABLE_SANITIZE=${{matrix.sanitizer}} \
              -DCMAKE_BUILD_TYPE=${{matrix.buildtype}}
            cmake --build build --target ${{matrix.target}}
            cmake --build build --target test
      - uses: actions/upload-artifact@v2
        with:
          name: freebsd-x64-${{matrix.name}}
          path: install/bin/*
          if-no-files-found: ignore
