name: linux
on:
  workflow_dispatch:
jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { name: dbg, preset: debug, target: install },
          { name: rel, preset: release, target: install/strip },
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - name: Run cmake
        run: |
          cmake --preset=${{ matrix.preset }} -DBUILD_TESTING=ON
          cmake --build --preset=${{ matrix.preset }} --target ${{ matrix.target }} --parallel
      - name: Run ctest
        run: |
          ctest --preset=${{ matrix.preset }} --parallel
      - uses: actions/upload-artifact@v2
        with:
          name: linux-x64-${{ matrix.name }}
          path: install/bin/*
          if-no-files-found: ignore
