name: mingw
on:
  workflow_dispatch:
jobs:
  MinGW:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { name: mingw64, triplet: x64-mingw-static },
          { name: mingw32, triplet: x86-mingw-static },
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - name: Run apt-get
        run: |
          set -x
          sudo apt-get -y update
          sudo apt-get -y install mingw-w64
      - name: Run cmake
        run: |
          set -x
          cmake -S . -B build \
            -DBUILD_TESTING=ON \
            -DENABLE_WARNINGS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=install \
            -DVCPKG_TARGET_TRIPLET=${{matrix.triplet}}
          cmake --build build --target install/strip
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.name}}-rel
          path: install/bin/*
          if-no-files-found: ignore
