name: msys2
on:
  workflow_dispatch:
jobs:
  MSYS2:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { name: mingw64, sys: MINGW64, triplet: x64-mingw-static },
          { name: mingw32, sys: MINGW32, triplet: x86-mingw-static },
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          location: D:\
          msystem: ${{matrix.sys}}
          pacboy: >-
            make:p
            cmake:p
            toolchain:p
      - name: Run cmake
        shell: msys2 {0}
        env:
          MSYSTEM: ${{matrix.sys}}
        run: |
          set -x
          cmake -S . -B build \
            -DBUILD_TESTING=ON \
            -DENABLE_WARNINGS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=install \
            -DVCPKG_TARGET_TRIPLET=${{matrix.triplet}}
          cmake --build build --target install/strip
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.name}}-rel
          path: install/bin/*
          if-no-files-found: ignore
      - name: Run ctest
        shell: msys2 {0}
        env:
          MSYSTEM: ${{matrix.sys}}
        run: |
          set -x
          cmake --build build --target test
